version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: Kirill
    environment:
      POSTGRES_DB: Task1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
